package org.fenixedu.sdk.domain;

public enum MissionState {

    APPROVAL, VERIFICATION, VEHICLE_AUTHORIZATION, FUND_ALLOCATION, PARTICIPATION_AUTHORIZATION, EXPENSE_AUTHORIZATION, ARCHIVED,
    PERSONAL_INFORMATION_PROCESSING;

}
